name: viola-jones
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - alabaster=0.7.10=py36h306e16b_0
  - anaconda-client=1.6.14=py36_0
  - asn1crypto=0.24.0=py36_0
  - babel=2.5.3=py36_0
  - bleach=2.1.3=py36_0
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36h0f667ec_1
  - clyent=1.2.2=py36h7e57e65_1
  - cryptography=2.2.1=py36h14c3975_0
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.12.2=hc3f9b76_1
  - decorator=4.2.1=py36_0
  - docutils=0.14=py36hb0f60f5_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py36h82fb2a8_1
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.2.1=py36h88c514a_1
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.1.2=py36_0
  - jedi=0.11.1=py36_1
  - jinja2=2.10=py36ha16c418_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - jupyterlab=0.31.12=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - kiwisolver=1.0.1=py36h764f252_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.7=h26e45fe_0
  - llvmlite=0.22.0=py36ha27ea49_0
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.2.2=py36h0e671d2_0
  - mistune=0.8.3=py36_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36h8118bb2_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - nbpresent=3.0.2=py36h5f95a39_1
  - ncurses=6.0=h9df7e31_2
  - notebook=5.4.1=py36_0
  - numba=0.37.0=np114py36h5fcf951_0
  - numpy=1.14.2=py36hdbf6ddf_1
  - numpydoc=0.7.0=py36h18f165f_0
  - olefile=0.45.1=py36_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py36_0
  - pandas=0.22.0=py36hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.1.1=py36h35f843b_0
  - patsy=0.5.0=py36_0
  - pcre=8.41=hc27e229_1
  - pexpect=4.4.0=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pillow=5.0.0=py36h3deb7b8_0
  - pip=9.0.1=py36_5
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36hf9f622e_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=17.5.0=py36h20ba746_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - pysocks=1.6.8=py36_0
  - python=3.6.5=hc3d631a_0
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.3=py36_0
  - pyyaml=3.12=py36hafb9ca4_1
  - pyzmq=17.0.0=py36h14c3975_0
  - qt=5.6.2=hd25b39d_14
  - qtconsole=4.3.1=py36h8f73b5b_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py36he2e5f8d_1
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.0.1=py36hfc37229_0
  - seaborn=0.8.1=py36hfad7ec4_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.0.1=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - snowballstemmer=1.2.1=py36h6febd40_0
  - sphinx=1.7.2=py36_0
  - sphinxcontrib=1.0=py36h6d0f590_1
  - sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
  - sqlite=3.22.0=h1bed415_0
  - statsmodels=0.8.0=py36h8533d0b_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.1=py36_1
  - traitlets=4.3.2=py36h674d592_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36hbe7ace6_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - wheel=0.30.0=py36hfd4bba0_1
  - widgetsnbextension=3.1.4=py36_0
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.3=h439df22_3
  - zlib=1.2.11=ha838bed_2
  - pip:
    - colorama==0.3.9
    - gitdb2==2.0.3
    - gitpython==2.1.9
    - nbdime==0.4.1
    - smmap2==2.0.3

